### ISSUE TITLE
Combat shotgun (And probably other cayo perico weapons) don't save.

### ISSUE THREAD

**Issue by thalilmythos** [justalemon/PlayerCompanion#13]

**Comment by justalemon** [comment]
This happens because PlayerCompanion uses the SHVDN enum to get the list of weapons, but it has not been updated with the new weapon hashes from The Cayo Perico Heist.

**Comment by justalemon** [comment]
Ill probably ask for some memory editing help on the 5mods server to get the weapon hashes directly from the game's memory during runtime.

**Comment by WithLithum** [comment]
RPH has a feature which you can get a collection of all weapons, just call ToList and then you can enumerate those, i think.

**Comment by justalemon** [comment]
Yes, but PlayerCompanion does not runs on RPH only on SHVDN.

**Comment by justalemon** [comment]
Looks like I forgot that I implemented this in fb9c95d743450f7d6bdf8ad227cdb43df4c93d61, whops!
