### ISSUE TITLE
Wanted stars don't get displayed anymore

### ISSUE THREAD

**Issue by vierse** [justalemon/PlayerCompanion#6]
PlayerCompanion 1.2 hides the wanted stars. The relevant code line is [here](https://github.com/justalemon/PlayerCompanion/blob/207e43cecb5310d1d88414f66d94b0782375b087/PlayerCompanion/Companion.cs#L152).

**Comment by justalemon** [comment]
Is funny that this was easy to fix after #8 lol.

Anyway, here it is:

![image](https://user-images.githubusercontent.com/11861253/118924253-d2a87900-b90a-11eb-8385-a65f62e8fcf7.png)
