### ISSUE TITLE
Money overlaps with ammo amount

### ISSUE THREAD

**Issue by WithLithum** [justalemon/PlayerCompanion#8]
![Grand Theft Auto V 2021_5_16 20_41_39](https://user-images.githubusercontent.com/37800788/118397605-71bd3e80-b687-11eb-826b-945e1234b7b4.png)
I created a simple script that allows player to buy weapons with custom models, and when you buy weapons, this happens.

**Comment by justalemon** [comment]
Sorry for the late fix, but here it is:

![image](https://user-images.githubusercontent.com/11861253/118923674-ec958c00-b909-11eb-98de-1c8f93cb7cbe.png)
