### ISSUE TITLE
Epic Games launcher not supported

### ISSUE THREAD

**Issue by demdem551** [justalemon/PlayerCompanion#9]
I use the epic games launcher and there are no scripts folder.
Can you make this mod supported by openIV as I cannot use a scripts folder.

**Comment by WithLithum** [comment]
Install https://github.com/crosire/scripthookvdotnet, then create a scripts folder, then drop this in.


Script mods cannot be installed via OpenIV.

**Comment by demdem551** [comment]
Thank you for the help :)
